version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Install build requirements
          command: |
            set -x
            apt-get update
            apt-get install -y make gcc cppcheck valgrind astyle poppler-utils colordiff
      - checkout
      - run:
          name: Build
          command: make
      - run:
          name: Test
          command: make check
