version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Install build requirements
          command: |
            set -x
            sudo apt-get update
            sudo apt-get install -y make gcc cppcheck valgrind astyle pdftotext
      - checkout
      - run:
          name: Build
          command: make
