version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
      - run: apt-get install make gcc cppcheck astyle valgrind
    steps:
      - checkout
      - run:
          name: Build
          command: make
